apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadie-backstage-plugins
  description: An example of a Backstage application.
spec:
  type: website 
  owner: group:open-source
  lifecycle: production

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: roadie-backstage-plugins
spec:
  targets:
    - ./plugins/**/catalog-info.yaml
    - ./utils/**/catalog-info.yaml