name: CI tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      CI: true
      NODE_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tsc
        run: yarn tsc

      - name: Run build
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev:ci
          wait-on: "http://localhost:3000, http://localhost:7007"
          project: ./packages/app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tsc
        run: yarn tsc

      - name: Run build
        run: yarn build

      - name: Run test
        run: yarn test
